workflows:
  flutter-app:
    name: Anime Habit Tracker Build
    environment:
      flutter: stable
    scripts:
      - name: Navigate to Flutter project folder
        script: cd anime_habit_tracker
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk
    artifacts:
      - anime_habit_tracker/build/app/outputs/flutter-apk/app-release.apk
